### PR TITLE
add two more maintainers links

### PR DESCRIPTION
**Pull request by SwiftyProgrammer690**
Added two more maintainer links for The Download and Africa Contributors for this @github repository for maintainer month!
Decided to take some time and contribute to this!

### CODE REVIEW

**Comment by SwiftyProgrammer690** [comment]
Please review this @blackgirlbytes or anyone for that matter who has write access to this repository!

**Review by karasowles — APPROVED** [review]

**Comment by SwiftyProgrammer690** [comment]
Hi @karasowles

**Comment by SwiftyProgrammer690** [comment]
Could you merge this if you feel like my changes are good? Thank you!

**Comment by SwiftyProgrammer690** [comment]
@karasowles after my checks are done?

**Comment by karasowles** [comment]
Yes! Waiting on checks :)

**Comment by SwiftyProgrammer690** [comment]
> Yes! Waiting on checks :)

thank you!

**Comment by SwiftyProgrammer690** [comment]
Just letting you know, i checked some other ones that updated the yml file and they took an hour so i don't know how long this is gonna take...

**Comment by SwiftyProgrammer690** [comment]
@karasowles the checks have completed!

**Comment by karasowles** [comment]
@SwiftyProgrammer690 thanks for the PR! Yay!

**Comment by SwiftyProgrammer690** [comment]
thank you!

**Pull request merged**
