### PR TITLE
Add 1st Open Source Stories MM story

### PR DESCRIPTION
**Pull request by juliaferraioli**
URL isn't live yet, FYI!

### CODE REVIEW

**Comment by abbycabs** [comment]
Thanks @juliaferraioli! I'll merge this in once it's live :)

**Comment by abbycabs** [comment]
I'll also wait til it's live to schedule some social

**Comment by juliaferraioli** [comment]
It's live! See https://www.opensourcestories.org/stories/2023/critical-human-infrastructure/

**Comment by abbycabs** [comment]
Website went live last night: https://maintainermonth.github.com/schedule/opensourcestories_duane_obrien

Social is going out at 1:32pm PT today

Thanks @juliaferraioli! Feel free to add placeholders for your other episodes and we can update links once they're live.

**Pull request merged**
