### PR TITLE
Create africameetup

### PR DESCRIPTION
**Pull request by karasowles**

### CODE REVIEW

**Comment by YuneVK** [comment]
Hi @karasowles!

A few comments about the event:

- The file extension should be `.md`.
- `title` is mandatory. Normally it will be the same as `metaTitle` (this one is used for SEO).
- In `description`, you don't need to include the text _(Description)_, so you can remove it.

If you can, fix it so we can add it to the page.

Thank you!

**Comment by karasowles** [comment]
@YuneVK Thank you! How does it look now?

**Comment by YuneVK** [comment]
A few more things:

The lines `---` included after the data are mandatory.

The description can be kept, in the previous comment I meant that the text in parentheses was not necessary. Before it was like this:

```
(Description)Join GitHub users across Africa to talk about open source project maintainership!

Speakers TBD, follow along on the Meetup page for announcements.
```

And I have edited it so that it looks like this:

```
Join GitHub users across Africa to talk about open source project maintainership!

Speakers TBD, follow along on the Meetup page for announcements.
```

To be able to launch the web today, I have edited the file correcting those two aspects. :)

If you have any doubts, once you have read the documentation, we can solve them in a meeting.

Thank you!

Translated with www.DeepL.com/Translator (free version)

**Comment by YuneVK** [comment]
A few more things:

The lines `---` included after the data are mandatory.

The description can be kept, in the previous comment I meant that the text in parentheses was not necessary. Before it was like this:

```
(Description)Join GitHub users across Africa to talk about open source project maintainership!

Speakers TBD, follow along on the Meetup page for announcements.
```

And I have edited it so that it looks like this:

```
Join GitHub users across Africa to talk about open source project maintainership!

Speakers TBD, follow along on the Meetup page for announcements.
```

To be able to launch the web today, I have edited the file correcting those two aspects. :)

If you have any doubts, once you have read the documentation, we can solve them in a meeting.

Thank you!

**Pull request merged**
